@startuml
actor Administrator
participant "Funkcjonalność logowania" as Logowanie
control UpdateController  /'Kontroler odpowiedzialny za zarządzanie aktualizacjami'/
database Database

Administrator -> Logowanie: Logowanie
activate Logowanie
Logowanie -> UpdateController: Administrator zalogowany
deactivate Logowanie
activate UpdateController

    UpdateController -> Database: Pobranie nowych elementów do zatwierdzenia
    activate Database
    Database --> UpdateController: Nowe elementy do zatwierdzenia
    deactivate Database
    UpdateController --> Administrator: Wyświetlenie elementów do zatwierdzenia

    alt Administrator zatwierdza dane
        Administrator -> UpdateController: Zatwierdzenie danych
        UpdateController -> Database: Zaktualizowanie danych w bazie
        activate Database
        Database --> UpdateController: Potwierdzenie aktualizacji
        deactivate Database
        UpdateController --> Administrator: Potwierdzenie zatwierdzenia danych
    else Administrator odrzuca dane
        Administrator -> UpdateController: Odrzucenie danych
        UpdateController -> Database: Aktualizacja danych jako niezaakceptowane
        activate Database
        Database --> UpdateController: Potwierdzenie aktualizacji
        deactivate Database
        UpdateController --> Administrator: Potwierdzenie odrzucenia danych
        deactivate UpdateController
    end

@enduml
