@startuml
actor Organizator
boundary EventForm  /'Formularz edycji wydarzenia'/
control EventController  /'Kontroler zarządzający logiką edycji wydarzenia'/
entity EventValidator  /'Walidator danych wydarzenia'/
database Database

Organizator -> EventForm: Wypełnienie i wysłanie formularza edycji
activate EventForm
EventForm -> EventController: POST /editEvent
deactivate EventForm
activate EventController
EventController -> EventValidator: Walidacja danych
activate EventValidator

alt Poprawne dane wydarzenia
    EventValidator --> EventController: Dane poprawne
    EventController -> Database: Zapisanie zaktualizowanych danych wydarzenia
    activate Database
    Database --> EventController: Potwierdzenie zapisu
    deactivate Database
    EventController --> Organizator: Potwierdzenie edycji i wysłania do zatwierdzenia
else Niepoprawne dane wydarzenia
    EventValidator --> EventController: Dane niepoprawne
    deactivate EventValidator
    EventController --> EventForm: Komunikat o błędnych danych
    deactivate EventController
    activate EventForm
    EventForm --> Organizator: Wyświetlenie komunikatu o błędnych danych
    deactivate EventForm
end
@enduml
